### ISSUE TITLE
Shiba cannot see changes inside hidden folders

### ISSUE THREAD

**Issue by xHN35RQ** [rhysd/Shiba#10]
Given a Markdown document inside a `.folder` Shiba cannot see any changes occuring to the document. Only on manual refresh can Shiba see the changes.

For example: writing a temporary Markdown document to `~/.cache/AppName/output.md` this file can be opened and manually refreshed inside Shiba but no changes made to that file will be automatically loaded by Shiba's watcher.

However, change that path to a non-hidden/non-dot folder `~/cache/AppName/output.md` and Shiba works beautifully, as normal.

Thanks!!

**Comment by xHN35RQ** [comment]
Ok this is because Shiba tells chokidar to ignore dotfiles as part of watcher.ts#L70

**Comment by rhysd** [comment]
Yeah, I added `'ignore_file_pattern'` config to `config.yml`. 

3896b3835396379be64a9a623fbeb750c45ec428

We can't know which file users want to ignore.  (They also may want to ignore `node_modules`)  It should be controlled by users.

**Comment by rhysd** [comment]
I renamed it to `'ignore_path_pattern'` because it matches to path (including directory), not file.

**Comment by xHN35RQ** [comment]
Wow this is great, thanks so much!! :tropical_drink:

**Comment by xHN35RQ** [comment]
After testing, this is still not working. I tried the following lines in my `config.yml` file and neither worked:

    ignore_path_pattern: '/\.git/'
    ignore_path_pattern: '[/\.git/]'

Am I entering the regex incorrectly?

Also, note that if I use double quotes instead of single quotes, Shiba tells me on commandline: `No configuration file is found`

**Comment by rhysd** [comment]
> ignore_path_pattern: '/\.git/'

Sorry for confusing.  It is a bit complicated. The string is passed to JavaScript's `RegExp`'s constructor.  So, I think `'/\\.git/'` is correct.

> Also, note that if I use double quotes instead of single quotes, Shiba tells me on commandline: No configuration file is found

Let me confirm a point.  You mean that above 'No configuration file is found' error does not occur when using single quotes?
Please be sure to put `config.yml` in `~/.config/Shiba` (I think already `Shiba` directory is created).

**Comment by xHN35RQ** [comment]
> You mean that above 'No configuration file is found' error does not occur when using single quotes?

No, ignore that. I made a mistake with regex which was causing the parser to consider the surrounding quotes as part of the regex, this was obviously problematic and caused the config file to fail loading.

**Comment by xHN35RQ** [comment]
Testing with: `ignore_path_pattern: '/\\.git/'` does not work. :cry:

**Comment by rhysd** [comment]
OK, I'll check it!

**Comment by xHN35RQ** [comment]
Shouldn't you pass the string directly to chokidar instead of a new `RegExp` instance?

**Comment by rhysd** [comment]
When the value of `ignored` is `string`, chokidar assumes it as the path  (See [here](https://github.com/paulmillr/chokidar/blob/master/index.js#L214)).
So I think we must make an instance of `RegExp`.

**Comment by rhysd** [comment]
In my environment, below configuration works.  (`README.md` is watched, `.foo.md` is watched and `.git/foo.md` is not watched)

```yaml
ignore_path_pattern: "/\\.git/"
```

Could you be sure that Shiba's version is v0.4.4?

**Comment by xHN35RQ** [comment]
Oooops. I am on 0.4.2. That's odd, because I updated Shiba right after I saw you create tag v0.4.4 however I wonder if npmjs.org is not serving 0.4.4?? Yep, just checked and it's on 0.4.2

**Comment by xHN35RQ** [comment]
Hmm, travis builds have been failing for a while now? https://travis-ci.org/rhysd/Shiba/builds

**Comment by rhysd** [comment]
Ah, that's right.  But I have received an error as below.  npm package already should be updated to 0.4.4...

```
npm ERR! publish Failed PUT 403
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 0.4.4." : shiba
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rhayasd/Dev/github.com/rhysd/Shiba/npm-publish/npm-debug.log
```

> Hmm, travis builds have been erroring for a while now?

I think it's not related to this issue.  It failed to open window in Travis environment.

Anyway, I think we should wait a little.  Thank you for your cooperation!

**Comment by xHN35RQ** [comment]
Ah ok. I will try some patience! :hourglass: Thanks for your help.

**Comment by xHN35RQ** [comment]
aaaand now it's 0.4.4. I'll update and test again.

**Comment by xHN35RQ** [comment]
Ok! 0.4.4 respects my setting of `ignore_path_pattern: "/\\.git/"` however I noted these 2 problems when Shiba watches a dot-folder, or any child of a dot-folder:

1. Shiba stops showing updates to watched document after 2nd or 3rd change, Watcher cannot see the changes
2. Shiba cannot see other files in same directory, Watcher cannot see file `adds` or any changes in other files

So for now, for my app I've moved my output to `/tmp/AppName/output1.md`, `/tmp/AppName/output2.md`, `/tmp/AppName/output3.md`, etc. and Shiba has no trouble with watching all the documents in `/AppName` - it works great.

**Comment by rhysd** [comment]
Sorry for late response.  I'll check it.

**Comment by rhysd** [comment]
I tried.

```
current dir --- .foo
                  |
                  |- animals.md
                  |
                  |- animals2.md
```

I prepared `.foo` directory, `animals.md` and `animals2.md`.  And I wrote below to `config.yml`

```yaml
ignore_path_pattern: '/\\.git/'
```

I started Shiba and drag&drop `animals.md` to the window.  And then I edited `animals.md`.
As the result,  I confirmed that Shiba works well.
Could you tell me your detailed sequence?

**Comment by xHN35RQ** [comment]
Hopefully this explains my problem further:

When editing a document inside a hidden folder, Shiba stops updating the document after the 2nd or 3rd update. Normally if you edit the document in Vim, upon saving the document Shiba will see the file change and update the document. However, after the 2nd or 3rd save in VIm, Shiba stops updating the document. This only occurs for files which have a dot folder somewhere in the path.

Also, when editing a document that has a dot folder somewhere in the path, Shiba cannot see any file events so if you start editing a document within that folder Shiba is unable to see it, and will not switch to the most recently changed file.

Neither of these problems occur when there is no dot-folder in the file path.

**Comment by rhysd** [comment]
Ah, sorry, I thought I wrote comment to this issue but I didn't...

Thank you for your detailed explanation.
I tried in above `.foo` directly but I could not reproduce...

1. I opened Shiba and loaded `animals.md` by clicking paw icon in main window.
2. I loaded `animals2.md` by folder button.
3. I edited `animals2.md`
4. Shiba updated preview correctly

**Comment by xHN35RQ** [comment]
Using the currently available build from npm, this is what happens:

1. folder `.foo` and `animals.md` inside `.foo`
2. open `animals.md` with shiba and with vim
3. edit in vim, upon `:w` no update in shiba, requires manual refresh, shiba cannot see changes
4. close shiba and vim
5. rename folder to `foo` and leave `animals.md` inside
6. reopen `animals.md` with shiba and vim
7. edit in vim, upon `:w` shiba sees changes and automatically updates

**Comment by xHN35RQ** [comment]
Oops didn't mean to close, pushed wrong button.

**Comment by rhysd** [comment]
Thank you for the detailed sequence.  I'll try it.

**Comment by rhysd** [comment]
@xHN35RQ 

I tried your sequence but `3.` still works well.
I took a screenshot.

![ss](https://dl.dropboxusercontent.com/u/2753138/shiba-bug.gif)

It may be a Linux-specific fsevent problem.  I'll check it with Ubuntu PC (I can't use Linux PC until next Thursday..)

**Comment by xHN35RQ** [comment]
Thanks @rhysd!

**Comment by rhysd** [comment]
I tried below sequence with shiba v0.5.1 and Ubuntu 12.04.  But it seems to work well...

### Directory

```
current dir --- .foo
                  |
                  |- animals.md
```

### Config

```yaml
ignore_path_pattern: '/\\.git/'
```

### Sequence

1. `cd .foo`
2. `vim animals.md`
3. `shiba animals.md`
4. Edit `animals.md` with Vim opened at `2.`.
5. Check preview

At 5., the preview was updated correctly.

**Comment by xHN35RQ** [comment]
I can confirm! I did not have `ignore_path_pattern: '/\\.git/'` in my config.yml. I added that line, and now it works perfectly.

So without `ignore_path_pattern: '/\\.git/'` in `config.yml` Shiba cannot see changes in dot-folders.

Thanks once again for your help! :cake:

**Comment by rhysd** [comment]
:tada:

Thank you for the confirmation.

**Comment by xHN35RQ** [comment]
In https://github.com/rhysd/Shiba/issues/10#issuecomment-142900717 you did the same as https://github.com/rhysd/Shiba/issues/10#issuecomment-133308065

So did I misunderstand something? Is Shiba default behavior to ignore hidden files?

**Comment by rhysd** [comment]
Yes, Shiba ignores dotfiles by default.
This is a standard way when using [chokidar](https://github.com/paulmillr/chokidar).

Sometimes dotfiles directory has many files (e.g. `.git` of large repository).  Watching such a directory seems to pay cost.  I think ignoring dotfiles helps to avoid the cost.

**Comment by xHN35RQ** [comment]
Well, thank you again for your help, and I'm sorry for causing all this extra work for you. I forgot to read the documentation after you updated on August 15.

**Comment by rhysd** [comment]
No problem.  You kindly reported many issues and they improved Shiba so much :smile:
