### ISSUE TITLE
不明なエラー（Markedっぽさ）

### ISSUE THREAD

**Issue by b4b4r07** [rhysd/Shiba#11]
とても便利なアプリをありがとうございます。

Version 0.4.0 を使っています。

ダウンロード後すぐに起動したところ、イカの、ではなくて以下のエラーが。

<img width="796" alt="2015-08-16 0 08 56" src="https://cloud.githubusercontent.com/assets/4442708/9289458/69ff3fa4-43ab-11e5-887a-ffec5af1f6ab.png">

「OK」すると D&D を催促するような画面が出てくるので、ファイルを D&D してみると次のエラーが出ます。

<img width="827" alt="2015-08-16 0 09 14" src="https://cloud.githubusercontent.com/assets/4442708/9289463/8ca91dae-43ab-11e5-9ccb-25a0f75dc0b1.png">

「OK」すると以下。

<img width="810" alt="2015-08-16 0 09 28" src="https://cloud.githubusercontent.com/assets/4442708/9289465/9d23c288-43ab-11e5-8bbf-740b8a2d37cc.png">

これ以降は、OK してもずっとこのエラーの繰り返しです。

PS.

関係ないかもしれませんが、最初のエラーが出るまでに数秒あります。その間に D&D すると表示されました。また、今回使った Markdown ファイルは Shiba 添付の README.md と個人的な *.md 数種類（うち一つには html タグが含まれている）です。

**Comment by rhysd** [comment]
報告ありがとうございます．
このポップアップウィンドウは `crash-reporter` というやつ（[こいつ](https://github.com/rhysd/Shiba/blob/master/src/browser/mainu.ts#L9)）が出していて，こいつが出ると100%バグです．

1回目でエラーが起きた後インスタンスが解放されてしまっていて，2回目以降は解放済みのリソースに別プロセスからアクセスしてエラーになっているようです．ですので，root cause は1回目っぽいですね．
エラーは marked の中で起きているみたいなので，見てみます．見た感じ marked に渡されるテキストが何故か文字列でなく `undefined` になっているようにみえます．

**Comment by rhysd** [comment]
@b4b4r07 

試しに修正してみました．

https://dl.dropboxusercontent.com/u/2753138/app.asar

下記のリンクからダウンロードした app.asar を Shiba.app/Contents/Resources/app.asar と差し替えてみてもらえませんでしょうか．app.asar が実は Shiba の本体で，差し替えると最新の v0.4.4 になります．

**Comment by b4b4r07** [comment]
@rhysd 

なるほど。

リンクの app.asar 試してみました。

差し替えて起動してみると例の起動時のエラーは出なかったぽいんですが、Shiba 添付の README.md を D&D するとエラー出ました。

<img width="510" alt="2015-08-16 6 36 47" src="https://cloud.githubusercontent.com/assets/4442708/9290973/bb8e3b78-43e1-11e5-9076-fa8bbfa51212.png">

OK してもう一度。

<img width="788" alt="2015-08-16 6 37 08" src="https://cloud.githubusercontent.com/assets/4442708/9290975/c6f05cee-43e1-11e5-933f-c3ed8fe28726.png">

エラーは出ませんが、このような感じです。

**Comment by rhysd** [comment]
ありがとうございます．
やはり僕の手元で起こせていないのがつらいですね… README.md で起きたとのことなので，再現手順を教えてもらえると助かります．

**Comment by b4b4r07** [comment]
こんな感じですね

![out](https://cloud.githubusercontent.com/assets/4442708/9291612/bcfcca40-4406-11e5-8d37-e977d7abb46b.gif)

**Comment by rhysd** [comment]
@b4b4r07 

分かりやすいスクリーンショットありがとうございます．
まったく同じ手順で v0.4.0 で試してみましたが再現しませんね… うーむ

**Comment by rhysd** [comment]
@b4b4r07 

どうにか再現することができました．
原因はどうやら `app.asar` のようです．`asar` 形式のファイルが監視ディレクトリにあるとハングして見せてもらったエラーが出ます．

`asar` は圧縮ファイルの形式なのですが，複数のファイルを1つにまとめるという機能だけを提供して，圧縮自体は行わずそれによって圧縮ファイルの中身に直接アクセスできる形式です．なので，ファイルの変更は取れるのですが，ファイルを読み込むことはできないので，そこでエラーが出ているようです．コレに関しては `asar` 形式のファイルが無いディレクトリで作業してもらえれば解決すると思うのですが，それで問題ないでしょうか？

**Comment by rhysd** [comment]
@b4b4r07 

修正してみました．Dropbox に置いた `app.asar` も更新してみたので，もしお時間あれば試してみていただけると助かります．（手元では直っていることを確認しています）
