### ISSUE TITLE
Improved Icon

### ISSUE THREAD

**Issue by xHN35RQ** [rhysd/Shiba#12]
I worked on the icon a little bit, to center the image within the frame, and also to remove a lot of the whitespace around the face. This makes it better for use as an icon. (I think :smile: ) Feel free to use it, if it's helpful.

![shibainu](https://cloud.githubusercontent.com/assets/9103375/9295208/6d3c07fa-441a-11e5-9212-0cf0d76e172b.png)

**Comment by rhysd** [comment]
Thank you! Very helpful.  Could you send pull request to put it in [here](https://github.com/rhysd/Shiba/tree/master/resource/image/icon)?  I'll make icons from it!

**Comment by xHN35RQ** [comment]
Sure! Thanks.

**Comment by xHN35RQ** [comment]
done!
