### ISSUE TITLE
Shiba v0.5.1 displays 2 scrollbars

### ISSUE THREAD

**Issue by xHN35RQ** [rhysd/Shiba#16]
I'm seeing an extra layer of scrollbars in Ubuntu 15.04 Gnome 3.14 GTK+ 3.14

![shiba](https://cloud.githubusercontent.com/assets/9103375/10039302/76ccd83e-6185-11e5-9af3-32113eacc9c4.png)

**Comment by rhysd** [comment]
Could you tell me your configuration (`config.yml`)?  It may helps to reproduce this bug.

**Comment by xHN35RQ** [comment]
Sure, but I tested this with and without `config.yml` in `~/.config/Shiba` and both conditions have the same issue.

```
drawer:
    responsive: false
file_ext:
    markdown:
        - "md"
        - "markdown"
        - "mkd"
        - "txt"
    html:
        - "html"
menu:
    visible: false
lint_options:
    list-item-indent: space
    maximum-line-length: false
    no-html: false
shortcuts:
    "g g": "PageTop"
    "shift+g": "PageBottom"
    ctrl+o: "ChangePath"
    i: ""
    m: ""
    q: "QuitApp"
```

**Comment by rhysd** [comment]
Thanks.  I'll try in Ubuntu.  At least this seems not to occur in OS X.

**Comment by garaemon** [comment]
I have the same issue on ubuntu.

![screenshot from 2015-09-23 19 45 28](https://cloud.githubusercontent.com/assets/40454/10043157/a5decb36-622b-11e5-88a6-de93854fa968.png)

**Comment by rhysd** [comment]
I could reproduce this with Ubuntu and fixed in ef9b296.  Default margin of `body` element caused this issue.

![](https://dl.dropboxusercontent.com/u/2753138/shiba-issue16.png)

I published Shiba v0.5.2.  Could you check it if you can?

**Comment by xHN35RQ** [comment]
It's fixed for me! Thanks!! :+1: 

I'll wait for @garaemon to report in before closing. But I imagine it's fixed for them as well.

**Comment by garaemon** [comment]
:+1: it's fixed!

**Comment by xHN35RQ** [comment]
awesome

**Comment by rhysd** [comment]
@xHN35RQ @garaemon Thanks!
