### ISSUE TITLE
Printing does not work because of `overflow: auto`

### ISSUE THREAD

**Issue by garaemon** [rhysd/Shiba#17]
I found printing does not work on shiba because of `overflow: auto`.

Scroll bar of shiba comes from `overflow: auto` but it may hide second and subsequent sheets.

[This patch](https://github.com/garaemon/Shiba/commit/675f9d908533768cecfb515b95300044a975f8d8) may resolve this issue but I don't know this is correct way to fix the issue.

**Comment by rhysd** [comment]
Hi.  Thank you for your report and patch!  I'll check it.

**Comment by garaemon** [comment]
By applying this patch, shiba can generate pdf like following (with default README.md):

![screenshot from 2015-09-23 19 55 19](https://cloud.githubusercontent.com/assets/40454/10043323/1669ed8a-622d-11e5-9fe3-5cbf8c293bd2.png)

But I'm afraid this patch is too tricky...

**Comment by rhysd** [comment]
I tried the patch.  But it can't be merged because drawer and preview are scrolled synchronously.  I think printer feature of Chrome has a collision with Polymer's drawer component.

**Comment by garaemon** [comment]
hmm, tough issue :sob:

**Comment by xHN35RQ** [comment]
Can you create a print-only style-sheet that only applies to printing?

**Comment by rhysd** [comment]
[media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) may help to solve this issue.  I'll try it!

**Comment by xHN35RQ** [comment]
> media query may help to solve this issue. I'll try it!

:four_leaf_clover:

**Comment by garaemon** [comment]
> media query may help to solve this issue. I'll try it!

:clap: awesome!

**Comment by rhysd** [comment]
Sorry for the delay.  I fixed as below.

![image](https://cloud.githubusercontent.com/assets/823277/10714712/3f130846-7b3e-11e5-83f8-6b8e9aea9312.png)

**Comment by xHN35RQ** [comment]
thanks this is fantastic. :+1: :trophy:
