### ISSUE TITLE
Cannot use mermaid.js

### ISSUE THREAD

**Issue by tuxtlequino** [rhysd/Shiba#19]
In your documentation, you mentioned that you can use mermaid.js by using mermaid code block, but in the 0.4.0 version of the mac app, this is not possible. When using the mermaid code block, the app simply uses a code block instead of using mermaid.

Am I missing something?

**Comment by rhysd** [comment]
Yes, please see [commit history](https://github.com/rhysd/Shiba/commits/master), it is added on 0.4.2.  So 0.4.0 doesn't support it.

**Comment by rhysd** [comment]
I'm planning to release 0.5.0 after #17 is fixed, but I currently take time for that...

**Comment by tuxtlequino** [comment]
Is there a way to download the newer versions? Thank you very much for the prompt response

**Comment by rhysd** [comment]
You can use npm package.  Or I can release app.asar for you.

**Comment by tuxtlequino** [comment]
I am in the process of installing the npm package, but If you could release the app, I would be very thankful. Agains, thank you.

**Comment by tuxtlequino** [comment]
Is it normal to take so long to install the nam package? My computer has been running the process for over two hours now.

**Comment by rhysd** [comment]
electron-prebuilt package downloads built electron binary.  It's size is 40~50 MB and it may takes long time.  Hmm... but 2hours is a bit odd...
OK, I'll make app.asar.

**Comment by rhysd** [comment]
I uploaded app.asar to my Dropbox account.  Please download it from [here](https://dl.dropboxusercontent.com/u/2753138/app.asar).

Then, replace app.asar in your Shiba app with new one.

- Windows: `resources/app.asar`
- Linux: `resources/app.asar`
- OS X: `Contents/Resources/app.asar`
