### ISSUE TITLE
Images embed broken

### ISSUE THREAD

**Issue by xHN35RQ** [rhysd/Shiba#2]
Embedding images do not render, this is broken: `![](shiba.png)`

VMD can do this, maybe looking at their code would show how to embed images? https://github.com/yoshuawuyts/vmd/blob/bc764bd589d7c31d8a25fd739b65c18bd6c39184/client.js#L9

Thank you.

**Comment by rhysd** [comment]
@xHN35RQ 

Thank you for your very helpful hint.  I fixed it in 2c138ca and released 0.3.7 for npm package.  If you use npm, please try it.  If you use standalone package, I'm sorry that please wait by next Monday.

**Comment by xHN35RQ** [comment]
:+1: Works well in 0.3.7 from npm! Thank you @rhysd :smile:

**Comment by rhysd** [comment]
:dog: :+1:
