### ISSUE TITLE
Arrows are not shown in mermaid block

### ISSUE THREAD

**Issue by toshi32tony3** [rhysd/Shiba#21]
使用するOS、ブラウザ、エディタに捉われずmarkdownをキレイにプレビューできて、かつmermaidが使える、とまさに求めていたものでした。素晴らしいアプリをリリースしてくださり、ありがとうございます。

さて、本題ですがmermaidで書いた図を表示してみると矢印が表示されないことが気になりました。
こちらは既知の問題でしょうか？

**Comment by rhysd** [comment]
報告ありがとうございます．

はい，既知の問題ですが，まだ解決できていない状態です．もし何か情報をお持ちでしたらいただけると助かります．

（英語圏の方にも issue の内容が把握できるよう，タイトルを変更しました）

**Comment by toshi32tony3** [comment]
返信、タイトルの修正ありがとうございます。状況を理解しました。
情報は持っていなかったので、mermaidのIssuesを確認したところ、それと思われるものがありました。

https://github.com/knsv/mermaid/issues/181

既知の問題で矢印が表示されない問題があったようです。既に修正が取り込まれていますが、まだリリースされていなかったようです。
私はWindows環境でnpmを使ってshibaをインストールしていたので、以下のフォルダをmermaidのmasterから取得したものと差し替えたところ、矢印が表示されることを確認しました。

%APPDATA%\npm\node_modules\shiba\bower_components\mermaid\dist

**Comment by rhysd** [comment]
おお，情報ありがとうございます．助かります．
どうやら mermaid のバージョンを 0.5.4 以上にすれば直りそうですね．Shiba のバージョンを 0.5.3 に上げる前に取り込みます．

**Comment by toshi32tony3** [comment]
対応の程よろしくお願いします！

**Comment by rhysd** [comment]
:muscle::dog:

**Comment by rhysd** [comment]
動作することが確認出来ました！
![shiba-mermaid](https://cloud.githubusercontent.com/assets/823277/11051806/bac5844c-8795-11e5-80c2-da7b2cd221f4.png)

**Comment by toshi32tony3** [comment]
Windows環境でも表示できることを確認しました。対応ありがとうございました！

**Comment by rhysd** [comment]
@toshi32tony3 

確認ありがとうございます！助かります．
