### ISSUE TITLE
typo and missing step in docs/installation.md

### ISSUE THREAD

**Issue by takkyun** [rhysd/Shiba#23]
Thank you for your such a great project.

I was following the instruction in https://github.com/rhysd/Shiba/blob/master/docs/installation.md#for-development

However I could not build an app without small modifications as follows:

```sh
$ gem install slimrb
```

In my environment (OSX 10.11), I could not find *slimrb* in gem repository.
So I did install *slim* instead.

```sh
$ gem install slim
```

===

```sh
# Build Shiba
$ rake build
```

When I run "rake build", at first it was failed with the following error:

```
No such file or directory - build/static/builtin-search.html
```

I need to create *build/static* directory before build:

```sh
# Build Shiba
$ mkdir ./build/static
$ rake build
```

Probably ```Rakefile``` should check existence of the output directory then create it if it's missing.

Regards,
Takuya

====

Shiba を公開していただき、ありがとうございます。

https://github.com/rhysd/Shiba/blob/master/docs/installation.md#for-development の手順通り、実行したのですが、以下の点でうまくいきませんでしたので、ご報告させていただきます。

```sh
$ gem install slimrb
```

私の環境では *slimrb* ではインストールできませんでした。

```sh
$ gem install slim
```

でインストールしました。

"rake build" を実行した際、

```
No such file or directory - build/static/builtin-search.html
```

というエラーが発生しました。build を実行する前に build/static ディレクトリを作成しておく必要があるようです。

```sh
# Build Shiba
$ mkdir ./build/static
$ rake build
```

```Rakefile``` で出力先ディレクトリの有無を確認して、ない場合はディレクトリを生成するようにした方がいいかもしれません。

以上、よろしくお願いいたします。
大谷

**Comment by rhysd** [comment]
丁寧なご報告ありがとうございます．
ドキュメントが古くなってしまっているようです。確認して修正し、完了後に issue close します．
