### ISSUE TITLE
Each errors are hidden, can't be seen whole.

### ISSUE THREAD

**Issue by koron** [rhysd/Shiba#26]
Can't see tail of messages on  Windows.

![shiba-error](https://cloud.githubusercontent.com/assets/468368/14401288/aa2810c2-fe47-11e5-9e04-c41042b57d7d.png)

It would be better pop up whole message when mouse cursor on it.

**Comment by rhysd** [comment]
I tried this with Shiba's README.md but it didn't reproduce :sob:

![default](https://cloud.githubusercontent.com/assets/823277/14420935/c52446ca-0009-11e6-8338-0167f9e6079d.JPG)

Could you tell me the OS version? (although I guess Windows10)

**Comment by rhysd** [comment]
Ah, I got it.  The drawer is expanded

**Comment by rhysd** [comment]
I tried with full window width to expand drawer, but it still did not reproduce :sob::sob:

![default](https://cloud.githubusercontent.com/assets/823277/14421030/4a1f01a8-000a-11e6-8f3d-4e906d3e3e44.JPG)

The scrollbar is shown properly in my environment (Windows 8.1).

**Comment by rhysd** [comment]
As a workaround, setting drawer non-responsible may be available to avoid this issue.

[Putting `config.yml` as below](https://github.com/rhysd/Shiba/blob/master/docs/customization.md)

```yaml
drawer:
    responsive: false
```

**Comment by koron** [comment]
Sorry my late response.

I met this for https://github.com/vim-jp/syntax-vim-ex/blob/master/README.md in Windows 10 env.
I'll test your suggestion later, please wait it.

**Comment by rhysd** [comment]
Thanks!  I'll also test with the README.

If you can, I'll happy to see the DOM (and CSS values applied to the drawer) with DevTools.
(In Windows, Alt key -> Click 'Shiba' -> Click 'DevTools' will launch DevTools.)

**Comment by koron** [comment]
Please verify my screen cast.

![01](https://cloud.githubusercontent.com/assets/468368/14422739/36e140fc-0013-11e6-9ef9-e2c43524cb78.gif)

My operations are as you expected?

**Comment by koron** [comment]
> Can't see tail of messages on Windows.

It means file name and line number.
Body of error message is shown whole.
(But it does not seem as good messsages :wink:)

**Comment by rhysd** [comment]
Yes, correct!  Thank you for so plain screenshot :smile_cat: 

It looks that the scroll issue occurs only when the drawer is expanded.

> It means file name and line number.

Yes, that's right.  I should fix this as another issue...

**Comment by rhysd** [comment]
Sorry, I misunderstood this issue.  You wrote '**Each** errors are hidden'.

You mean below message has lost its tail?

> List item should be loose, isn't

**Comment by koron** [comment]
I was going to have reported two things.

1. filename and line number is hidden.
2. It looks like that some kind of important info was removed from `List item should be loose, isn't` 

Sorry for ambiguous notation.

**Comment by rhysd** [comment]
Thank you for making it clear.

> filename and line number is hidden.

This was fixed in #29, thank you for reporting.


> It looks like that some kind of important info was removed from List item should be loose, isn't

Actually that's all of message from linter.

```
$ remark synta-vim-ex-README.md -u remark-lint

syntax-vim-ex-README.md
        1:1   warning  Do not mix casing in file names                no-file-name-mixed-case
   6:1-6:43   warning  Headings should use setext                     heading-style
  9:36-10:1   warning  List item should be loose, isn’t               list-item-spacing
  11:39-12:1  warning  List item should be loose, isn’t               list-item-spacing
  12:48-13:1  warning  List item should be loose, isn’t               list-item-spacing
  15:1-15:15  warning  Headings should use setext                     heading-style
  19:1-19:18  warning  Headings should use setext                     heading-style
  21:1-26:4   warning  Do not use dollar signs before shell-commands  no-shell-dollars
  37:78-38:1  warning  List item should be loose, isn’t               list-item-spacing
  38:52-39:1  warning  List item should be loose, isn’t               list-item-spacing
  40:64-41:1  warning  List item should be loose, isn’t               list-item-spacing
  44:1-44:17  warning  Headings should use setext                     heading-style
  46:1-49:4   warning  Do not use dollar signs before shell-commands  no-shell-dollars
  51:1-51:11  warning  Headings should use setext                     heading-style
  55:1-55:11  warning  Headings should use setext                     heading-style

⚠ 15 warnings
```

Exactly the `... is't` message looks weird...

**Comment by rhysd** [comment]
@koron 

Can we close this?

**Comment by koron** [comment]
:+1: thanks!
