### ISSUE TITLE
Remember position and size of window.

### ISSUE THREAD

**Issue by koron** [rhysd/Shiba#27]
When restarting shiba after changed window size and position, it was reseted.

I have realize this with Windows 64bit version.

![shiba](https://cloud.githubusercontent.com/assets/468368/14401318/ae17f408-fe48-11e5-8819-87aa5b8e0c32.gif)

**Comment by rhysd** [comment]
I implemented restoring last window state at app starting in acffd0e.  I tested this on OS X 10.11.4 and Windows 8.1.

This improvement will come with 1.0.1 release :+1:
