### ISSUE TITLE
Overhead CPU MacOS

### ISSUE THREAD

**Issue by arielril** [rhysd/Shiba#35]
Whenever I open Shiba, with or without a file, my CPU percentage goes up to 180%.

**Comment by rhysd** [comment]
How did you install and launch Shiba?

**Comment by arielril** [comment]
I've installed with brew and started at the applications folder and after that I've installed with your download package for Mac os and the same thing to open

**Comment by rhysd** [comment]
ok, I'll try to repro. CPU usage is often high when watching directory has so many entries.

**Comment by arielril** [comment]
Thanks

**Comment by rhysd** [comment]
I tried this but Shiba only takes 0.8% of CPU.

Shiba watches `~/Documents` by default on macOS. Do you have so many files in the directory?

**Comment by arielril** [comment]
Yes, I have a lot of files there

**Comment by rhysd** [comment]
ok, I'll find a directory which contains so many files and try with it.

**Comment by rhysd** [comment]
Could you tell me the number of entities in `~/Documents` by following command?

```
$ find ~/Documents -type f | wc -l
```

And is there any symbolic link which makes a loop?

**Comment by arielril** [comment]
I executed the command and the result was 165810. I dont have any symbolic link in that folder, as far as I know.

**Comment by arielril** [comment]
Thanks for help :D
