### ISSUE TITLE
Syntax Hightlighting

### ISSUE THREAD

**Issue by jonaprieto** [rhysd/Shiba#39]
I'm using code blocks but in the preview, they don't look like in Github (with colors).
I'm working with code written in Agda.

Any reason?

**Comment by rhysd** [comment]
Please describe following:

- Markdown document you wrote
- Expected result
- Actual result (screenshot would help much)
- Your environment
  - Shiba version
  - OS
  - How did you install Shiba? (From release page/`npm install`/homebrew-cask)

**Comment by jonaprieto** [comment]
Using this after installing with homebrew-cask.
![image](https://user-images.githubusercontent.com/1428088/32412740-7ba9a7f4-c1cf-11e7-88e3-921fa8fbe17a.png)
In Shiba:
![image](https://user-images.githubusercontent.com/1428088/32412745-9849d578-c1cf-11e7-9074-6e69bd5c7339.png)
It should look like:
![image](https://user-images.githubusercontent.com/1428088/32412748-b3a0d6f0-c1cf-11e7-80f7-9cb12cf55a92.png)

The source code was taken from:
https://github.com/jonaprieto/agda-prop/blame/master/README.md#L17-L40

**Comment by rhysd** [comment]
Thank you for the info. Shiba utilizes highlight.js for highlighting codes. I guess Agda is not supported by it. It may be spported by upgrading highlight.js. I'll check it.

**Comment by rhysd** [comment]
I checked highlighters in highlight.js. It supports 176 languages, but Agda is not included in them.

In order to support Agda by Shiba, we need to add Agda syntax highlighter to highlight.js. So I can't fix this in Shiba side. Could you please make an issue or PR in highlight.js repo?
