### ISSUE TITLE
Inline math rendering possible?

### ISSUE THREAD

**Issue by Hananja** [rhysd/Shiba#40]
I am amazed about this software. I searched for exactly such a live preview application. Thank you for this.

But I could not figure out how to render inline math with katex. I tried 

```
Lorem ipsum `\lambda`{.katex}
```

but it does not work. Is there any war to render inline math with Shiba?

**Comment by rhysd** [comment]
Shiba utilizes [marked](https://github.com/chjj/marked) as markdown parser. And it does not support extra syntax parsing. So for now there is no way to add the syntax.

**Comment by Hananja** [comment]
I see. But that's too bad. 

Thank you for you reply anyway.
