### ISSUE TITLE
Is there any chance to support another latex rendering

### ISSUE THREAD

**Issue by jonaprieto** [rhysd/Shiba#41]
What the title says but using this:

[Latex render service](
https://tex.s2cms.com/)

The service above is pretty good and I'm using for some README in github.
Maybe Shiba could support it.

In order to have something like this:

https://upmath.me/

**Comment by rhysd** [comment]
Shiba already supports [katex](https://khan.github.io/KaTeX/). Could you tell me why katex is not enough for you?

**Comment by jonaprieto** [comment]
Katex is very well-known, but tex.s2cms.com render has more features of latex supported than Katex.
To just mention one feature, It has support to plot figures made by using Tikz package (very popular and Katex doesn't). Other packages like bussproofs to plot trees in Logic are supported too. 

And its author helps users if some latex package is not supported. Katex has still many open issues ~150 and it is fast, but take a look to upmath editor, it's fast too.

**Comment by rhysd** [comment]
Hmm, thank you for your explanation. Shiba is a markdown previewer and intends to use katex for math rendering, does not intend to preview full latex document.

And for LaTeX, I think there are already many nice previewers which support full features of LaTeX. So IMO it would be better to use them.

**Comment by jonaprieto** [comment]
> does not intend to preview full latex document.

Sure. There are other tools/programa for that. Who wants to render a full latex?

> And for LaTeX, I think there are already many nice previewers which support full features of LaTeX. So IMO it would be better to use them.

Which ones?

> and intends to use katex for math rendering, 

You made your point, so I close this issue.
