### ISSUE TITLE
3rd consequtive drag and drop breaks rendering

### ISSUE THREAD

**Issue by xHN35RQ** [rhysd/Shiba#5]
If I drag and drop multiple files into same Shiba window, on the 3rd (and sometimes 4th) drag and drop, the rendering breaks and it only shows just text in monospace font.

Not sure if this is really an issue, since I'm not sure how often drag and drop is used. :smile:

**Comment by rhysd** [comment]
Thank you for your report.  I could reproduce this bug!

**Comment by xHN35RQ** [comment]
No thank you. I just wish I was better with JS so I could submit pull requests instead of issues.

**Comment by rhysd** [comment]
I fixed this bug in f7bcbb2 and released 0.3.11.  Could you check this issue is solved with the latest version?

**Comment by xHN35RQ** [comment]
:+1: it's fixed :traffic_light: full speed ahead!

**Comment by rhysd** [comment]
:dancers:
