### ISSUE TITLE
Add CSS styling to Documentation

### ISSUE THREAD

**Issue by xHN35RQ** [rhysd/Shiba#7]
I just noticed on `0.4.0` release notes the reference to `{config dir}/user.css` which I assume is custom CSS stylesheet?

If so, perhaps you could place an example CSS in the Documentation so we have reference for all the various CSS selectors available to style Shiba's output. Then I can get started on `tufte-css` :smile:

**Comment by rhysd** [comment]
@xHN35RQ 

Yes, custom CSS.

I added document!
https://github.com/rhysd/Shiba/blob/master/docs/customization.md#user-css

**Comment by rhysd** [comment]
> Then I can get started on tufte-css

Oh, it may not be possible.  Markdown preview area is isolated by `<markdown-preview>` web component.  It is not possible to apply stylesheets to inside of web component from outside.

**Comment by xHN35RQ** [comment]
> It is not possible to apply stylesheets to inside of web component from outside.

Ohhh, that's too bad. Does it need a LESS version of `tufte-cess`?

**Comment by rhysd** [comment]
It's not a problem of file format.  WebComponents encapsulates styles in its component.  So we can't modify it from index.html.

I agree that tufte-css is very nice, so I already added the tufte theme to [TODO list](https://github.com/rhysd/Shiba#todos).  And I also create issue #9 for that.

**Comment by xHN35RQ** [comment]
Ok cool. thanks.
